/// نصوص التطبيق - للغة العربية والإنجليزية
class AppStrings {
  static final Map<String, Map<String, String>> _strings = {
    'ar': {
      'profile': 'الملف الشخصي',
      'signInToContinue': 'سجّل الدخول للمتابعة',
      'manageDataSubtitle': 'يمكنك إدارة بياناتك وحجوزاتك وتتبع النتائج',
      'signIn': 'تسجيل الدخول',
      'createAccount': 'إنشاء حساب جديد',
      'editProfile': 'تعديل الملف الشخصي',
      'quickAccess': 'الوصول السريع',
      'myBookings': 'حجوزاتي',
      'bookingsSubtitle': 'عرض وإدارة الحجوزات',
      'favorites': 'المفضلة',
      'favoritesSubtitle': 'المختبرات والتحاليل المفضلة',
      'settings': 'الإعدادات',
      'settingsSubtitle': 'تخصيص التطبيق',
      'help': 'المساعدة',
      'helpSubtitle': 'الأسئلة الشائعة والدعم',
      'logout': 'تسجيل الخروج',
      'logoutSubtitle': 'الخروج من الحساب',
      'logoutConfirm': 'تسجيل الخروج',
      'logoutConfirmMessage': 'هل أنت متأكد من تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'language': 'اللغة',
      'darkMode': 'الوضع الداكن',
      'arabic': 'العربية',
      'english': 'English',
      'preferences': 'التفضيلات',
    },
    'en': {
      'profile': 'Profile',
      'signInToContinue': 'Sign in to continue',
      'manageDataSubtitle': 'Manage your data, bookings and track results',
      'signIn': 'Sign In',
      'createAccount': 'Create Account',
      'editProfile': 'Edit Profile',
      'quickAccess': 'Quick Access',
      'myBookings': 'My Bookings',
      'bookingsSubtitle': 'View and manage bookings',
      'favorites': 'Favorites',
      'favoritesSubtitle': 'Favorite labs and analyses',
      'settings': 'Settings',
      'settingsSubtitle': 'Customize the app',
      'help': 'Help',
      'helpSubtitle': 'FAQ and support',
      'logout': 'Logout',
      'logoutSubtitle': 'Sign out of account',
      'logoutConfirm': 'Logout',
      'logoutConfirmMessage': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'language': 'Language',
      'darkMode': 'Dark Mode',
      'arabic': 'العربية',
      'english': 'English',
      'preferences': 'Preferences',
    },
  };

  static String t(String key, String lang) => _strings[lang]?[key] ?? _strings['ar']![key]!;
}
