/// نصوص التطبيق — واجهة عصرية وواضحة (عربي / إنجليزي)
class AppStrings {
  static final Map<String, Map<String, String>> _strings = {
    'ar': {
      'appName': 'راست',
      'profile': 'حسابي',
      'signInToContinue': 'سجّل الدخول للوصول إلى كل المزايا',
      'manageDataSubtitle': 'ادفع حجوزاتك، تتبع النتائج، وادير بياناتك من مكان واحد',
      'signIn': 'دخول',
      'createAccount': 'إنشاء حساب',
      'editProfile': 'تعديل البيانات',
      'quickAccess': 'اختصارات',
      'myBookings': 'حجوزاتي',
      'bookingsSubtitle': 'مواعيدك القادمة والسابقة',
      'favorites': 'المفضلة',
      'favoritesSubtitle': 'مختبراتك وتحاليلك المحفوظة',
      'settings': 'الإعدادات',
      'settingsSubtitle': 'اللغة، الإشعارات، والمظهر',
      'help': 'المساعدة',
      'helpSubtitle': 'أسئلة شائعة وتواصل مع الدعم',
      'logout': 'خروج',
      'logoutSubtitle': 'الخروج من الحساب',
      'logoutConfirm': 'تسجيل الخروج',
      'logoutConfirmMessage': 'هل تريد الخروج من حسابك؟',
      'cancel': 'إلغاء',
      'language': 'اللغة',
      'darkMode': 'الوضع الداكن',
      'arabic': 'العربية',
      'english': 'English',
      'preferences': 'التفضيلات',
      'home': 'الرئيسية',
      'bookings': 'الحجوزات',
      'labs': 'المختبرات',
      'greeting': 'أهلاً',
      'greetingWithName': 'أهلاً، %s',
      'searchHint': 'تحليل، مختبر، أو باقة...',
      'filterResults': 'تصفية البحث',
      'categories': 'تصنيفات التحاليل',
      'viewAll': 'الكل',
      'viewAllOffers': 'كل العروض',
      'packages': 'باقات الفحص',
      'featuredLabs': 'مختبرات موثوقة',
      'offers': 'عروض مميزة',
      'loadError': 'لم نتمكن من تحميل البيانات',
      'retry': 'إعادة المحاولة',
      'checkConnection': 'تحقق من الاتصال بالإنترنت أو إعدادات الـ API',
      'loginTitle': 'مرحباً بعودتك',
      'loginSubtitle': 'سجّل الدخول لمتابعة حجوزاتك ونتائجك',
      'email': 'البريد الإلكتروني',
      'emailHint': 'example@email.com',
      'password': 'كلمة المرور',
      'passwordHint': '••••••••',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'loginButton': 'دخول',
      'noAccount': 'ليس لديك حساب؟ ',
      'emailRequired': 'أدخل البريد الإلكتروني',
      'emailInvalid': 'بريد إلكتروني غير صحيح',
      'passwordRequired': 'أدخل كلمة المرور',
      'notifications': 'التنبيهات',
      'bookingReminders': 'تذكيرات المواعيد',
      'bookingRemindersDesc': 'استلام تذكيرات قبل المواعيد والتحديثات',
      'promoNotifications': 'العروض والإعلانات',
      'promoNotificationsDesc': 'إشعارات بالخصومات والعروض',
      'appSection': 'التطبيق',
      'defaultLocation': 'الموقع الافتراضي',
      'defaultLocationDesc': 'لإظهار المختبرات الأقرب لك',
      'darkModeOn': 'مفعّل',
      'darkModeOff': 'معطّل',
      'testsCount': 'تحليل',
      'homeService': 'منزلي',
      'sar': 'ر.س',
      'contactForPrice': 'اتصل للمعرفة',
      'bookingsSignInPrompt': 'سجّل الدخول لعرض حجوزاتك',
      'support': 'الدعم',
      'faq': 'الأسئلة الشائعة',
      'contactUs': 'تواصل معنا',
      'terms': 'الشروط والأحكام',
      'chat': 'المساعد',
      'chatHint': 'اكتب رسالتك...',
      'chatSignIn': 'سجّل الدخول لاستخدام المساعد',
      'send': 'إرسال',
    },
    'en': {
      'appName': 'Rast',
      'profile': 'Profile',
      'signInToContinue': 'Sign in to access all features',
      'manageDataSubtitle': 'Pay bookings, track results, and manage your data in one place',
      'signIn': 'Sign In',
      'createAccount': 'Create Account',
      'editProfile': 'Edit Profile',
      'quickAccess': 'Shortcuts',
      'myBookings': 'My Bookings',
      'bookingsSubtitle': 'Upcoming and past appointments',
      'favorites': 'Favorites',
      'favoritesSubtitle': 'Saved labs and tests',
      'settings': 'Settings',
      'settingsSubtitle': 'Language, notifications, and appearance',
      'help': 'Help',
      'helpSubtitle': 'FAQ and support',
      'logout': 'Logout',
      'logoutSubtitle': 'Sign out',
      'logoutConfirm': 'Logout',
      'logoutConfirmMessage': 'Do you want to sign out?',
      'cancel': 'Cancel',
      'language': 'Language',
      'darkMode': 'Dark Mode',
      'arabic': 'العربية',
      'english': 'English',
      'preferences': 'Preferences',
      'home': 'Home',
      'bookings': 'Bookings',
      'labs': 'Labs',
      'greeting': 'Hi',
      'greetingWithName': 'Hi, %s',
      'searchHint': 'Test, lab, or package...',
      'filterResults': 'Filter results',
      'categories': 'Test categories',
      'viewAll': 'All',
      'viewAllOffers': 'All offers',
      'packages': 'Checkup packages',
      'featuredLabs': 'Trusted labs',
      'offers': 'Special offers',
      'loadError': 'Could not load data',
      'retry': 'Retry',
      'checkConnection': 'Check your internet or API settings',
      'loginTitle': 'Welcome back',
      'loginSubtitle': 'Sign in to manage bookings and results',
      'email': 'Email',
      'emailHint': 'example@email.com',
      'password': 'Password',
      'passwordHint': '••••••••',
      'forgotPassword': 'Forgot password?',
      'loginButton': 'Sign In',
      'noAccount': "Don't have an account? ",
      'emailRequired': 'Enter your email',
      'emailInvalid': 'Invalid email',
      'passwordRequired': 'Enter your password',
      'notifications': 'Notifications',
      'bookingReminders': 'Booking reminders',
      'bookingRemindersDesc': 'Get reminders before appointments and updates',
      'promoNotifications': 'Offers & promotions',
      'promoNotificationsDesc': 'Alerts for discounts and offers',
      'appSection': 'App',
      'defaultLocation': 'Default location',
      'defaultLocationDesc': 'To show labs near you',
      'darkModeOn': 'On',
      'darkModeOff': 'Off',
      'testsCount': 'tests',
      'homeService': 'Home',
      'sar': 'SAR',
      'contactForPrice': 'Contact for price',
      'bookingsSignInPrompt': 'Sign in to view your bookings',
      'support': 'Support',
      'faq': 'FAQ',
      'contactUs': 'Contact us',
      'terms': 'Terms & conditions',
      'chat': 'Assistant',
      'chatHint': 'Type your message...',
      'chatSignIn': 'Sign in to use the assistant',
      'send': 'Send',
    },
  };

  static String t(String key, String lang) =>
      _strings[lang]?[key] ?? _strings['ar']![key]!;

  static String tParam(String key, String lang, String param) {
    final s = t(key, lang);
    return s.replaceAll('%s', param);
  }
}
